apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl
    app.kubernetes.io/part-of: mc-two-scenarios
  name: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-springboot-app
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-springboot-app
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mnty-tenant/mc-two-scenarios/devfile-sample-java-springboot-basic-rhtap-devfile-multi-c-oisl@sha256:1e9ad9ef7f7f8dec56a89b89fac45358ad38e85eb722598603efefd18a19ad9e
        name: my-java-springboot
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
